version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/sami/docker/portainer/data:/data
      - /home/sami/docker/portainer/configs:/conf
    ports:
      - 9443:9443